[project]
name = "loc2vec"
version = "0.1.0"
description = "Project for ML"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.0.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "rasterio>=1.4.3",
    "shapely>=2.0.7",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
